erver:
  port: 8090

management:
  endpoint:
    health:
      group:
        disk:
          include: diskSpace
          show-components: always
          show-details: always
        ping:
          include: ping
          show-components: never
          show-details: always

spring:
  datasource:
    url: jdbc:h2:file:c:/tmp/data/db
  jpa:
    hibernate:
      ddl-auto: update